[package]
name = "argus-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
argus-core.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
